export const subjectEnumMap: Record<string, string> = {
  mathematics: "MATHEMATICS",
  physics: "PHYSICS",
  english: "ENGLISH",
  afrikaans: "AFRIKAANS",
  natural_sciences: "NATURAL_SCIENCES",
  social_sciences: "SOCIAL_SCIENCES",
  life_skills: "LIFE_SKILLS",
  economic_management: "ECONOMIC_MANAGEMENT",
  accounting: "ACCOUNTING",
  business_studies: "BUSINESS_STUDIES",
  economics: "ECONOMICS",
  geography: "GEOGRAPHY",
  history: "HISTORY",
  life_sciences: "LIFE_SCIENCES",
  technology: "TECHNOLOGY",
  general: "GENERAL",
  MATHEMATICS: "MATHEMATICS",
  PHYSICS: "PHYSICS",
  ENGLISH: "ENGLISH",
};
